<a href="https://colab.research.google.com/github/Lameeselbakr55/NTI_AI_Projects/blob/master/MNIST_Binary_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MNIST Binary Logistic Regression

##Loading and Preparing Data

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
y_train[0:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [ ]:
#we create new variables that contain only zeros and ones.
x_train_binary= x_train[(y_train==0) | (y_train==1)]
y_train_binary= y_train[(y_train==0) | (y_train==1)]

#Let’s check the shape of the new variables.
x_train_binary.shape

(12665, 28, 28)

In [ ]:
print(y_train[0:10]) 
print(y_train_binary[0:10])

[5 0 4 1 9 2 1 3 1 4]
[0 1 1 1 1 0 1 1 0 0]


In [ ]:
#we need to flatten data into two dimensions only: (28 * 28 = 784).

x_train_final = x_train_binary.reshape((-1, 784))
x_train_final.shape

(12665, 784)

In [ ]:
#A similar sequence of operations we perform for the test set.

x_test_binary= x_test[(y_test==0) | (y_test==1)]
y_test_binary= y_test[(y_test==0) | (y_test==1)]
x_test_binary.shape

(2115, 28, 28)

In [ ]:
x_test_final = x_test_binary.reshape((-1, 784))
x_test_final.shape

(2115, 784)

In [ ]:
#The last element of data preprocessing is their normalization.

x_train_final = x_train_final / 255
x_test_final = x_test_final / 255

##Model Fitting

In [ ]:
model=LogisticRegression()


In [ ]:
model.fit(x_train_final,y_train_binary)  

LogisticRegression()

##Results

In [ ]:
y_pred= model.predict(x_test_final)

In [ ]:
y_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=uint8)

In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
accuracy_score(y_test_binary,y_pred)*100

99.95271867612293