<a href="https://colab.research.google.com/github/amrtariq/NTI_AI_Projects/blob/main/Cifar10_ANN_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Testing ANN on Cifar10 Dataset

##Data Loading and Preparing

In [ ]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt


In [ ]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

170508288/170498071 [==============================] - 3s 0us/step


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train, test_size=0.3)

In [ ]:
x_train.shape

(35000, 32, 32, 3)

In [ ]:
x_val.shape

(15000, 32, 32, 3)

In [ ]:
x_test.shape

(10000, 32, 32, 3)

In [ ]:
#Normalize image pixel values.
x_train = x_train/255
x_val = x_val/255
x_test=x_test/255

##Model Fitting

In [ ]:
model=keras.Sequential() #Create a network sequence.
model.add(Input(shape=(32,32,3)))
model.add(Flatten())
model.add(Dense(256,activation = 'relu'))
model.add(Dense(128,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 3072)              0         
                                                                 
 dense (Dense)               (None, 256)               786688    
                                                                 
 dense_1 (Dense)             (None, 128)               32896     
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 820,874
Trainable params: 820,874
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
#model.compile(optimizer='Adam',loss="categorical_crossentropy",metrics=['accuracy']) 


In [ ]:
x_val.shape

(15000, 32, 32, 3)

In [ ]:
batch_size=128
results= model.fit(x_train,y_train,epochs=20,validation_data=(x_val, y_val),
                   steps_per_epoch=x_train.shape[0]/batch_size,validation_steps=x_val.shape[0]/batch_size)

Epoch 1/20
273/273 [==============================] - 7s 20ms/step - loss: 1.9597 - accuracy: 0.3003 - val_loss: 1.8153 - val_accuracy: 0.3483
Epoch 2/20
273/273 [==============================] - 4s 15ms/step - loss: 1.7505 - accuracy: 0.3751 - val_loss: 1.6950 - val_accuracy: 0.3955
Epoch 3/20
273/273 [==============================] - 4s 15ms/step - loss: 1.6778 - accuracy: 0.4010 - val_loss: 1.7204 - val_accuracy: 0.3843
Epoch 4/20
273/273 [==============================] - 4s 16ms/step - loss: 1.6124 - accuracy: 0.4253 - val_loss: 1.6639 - val_accuracy: 0.4015
Epoch 5/20
273/273 [==============================] - 4s 15ms/step - loss: 1.5706 - accuracy: 0.4414 - val_loss: 1.6069 - val_accuracy: 0.4237
Epoch 6/20
273/273 [==============================] - 4s 15ms/step - loss: 1.5365 - accuracy: 0.4525 - val_loss: 1.5636 - val_accuracy: 0.4411
Epoch 7/20
273/273 [==============================] - 4s 15ms/step - loss: 1.5128 - accuracy: 0.4625 - val_loss: 1.5505 - val_accuracy: 0.4518

##Results

In [ ]:
score_val = model.evaluate(x_val, y_val)


469/469 [==============================] - 1s 3ms/step - loss: 1.4670 - accuracy: 0.4885


In [ ]:
score_test = model.evaluate(x_test, y_test)


313/313 [==============================] - 1s 3ms/step - loss: 1.4440 - accuracy: 0.4924


In [ ]:
y_pred_val=model.predict(x_val)
y_pred_val.shape

(15000, 10)

In [ ]:
from numpy import argmax
y_pred_val1=argmax(y_pred_val,axis=1)
y_pred_val1.shape

(15000,)

In [ ]:
from sklearn.metrics import accuracy_score,  confusion_matrix
accuracy_score(y_val,y_pred_val1)*100

48.846666666666664

In [ ]:
# testing the model by  x_test
y_pred_test=model.predict(x_test)
y_pred_test1=argmax(y_pred_test,axis=1)
accuracy_score(y_test,y_pred_test1)*100

49.24

In [ ]:
print(confusion_matrix(y_test,y_pred_test1))

[[535  58  34  11  46  43  13  72 155  33]
 [ 35 729   9   9   9  34  16  22  53  84]
 [ 76  34 306  49 172 122  86 114  27  14]
 [ 23  53  70 220  88 297  95  89  31  34]
 [ 51  25 106  27 467  70  97 134  20   3]
 [ 18  27  54 130  89 477  53 111  23  18]
 [ 15  32  84  54 139 104 502  39  13  18]
 [ 40  36  33  28  88  95  23 623  12  22]
 [ 98  95   8  12  35  37   6  24 637  48]
 [ 48 287  11  18  25  32  20  65  66 428]]
